service: qr-code-v1
provider:
  name: aws
  runtime: nodejs14.x 
  stage: dev
  region: us-east-1
  
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /qr
          method: GET
          cors: true
    
plugins:
  - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - '*/*'

